language: emacs-lisp
matrix:
  env:
    - EMACS=emacs-24.3
    - EMACS=emacs-25.1
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs-snapshot emacs25

script:
  - $EMACS --version
  - $EMACS -batch -l clj-parse-test-runner.el
