language: emacs-lisp
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs-snapshot

script:
  - emacs -batch -l clj-parse-test-runner.el
