language: emacs-lisp
matrix:
  env:
    - EMACS=emacs-24.3
      PPA=ppa:ubuntu-elisp
      PACKAGE=emacs-snapshot
    - EMACS=emacs-25.1
      PPA=ppa:kelleyk/emacs
      PACKAGE=emacs25

before_install:
  - sudo add-apt-repository -y $PPA
  - sudo apt-get update -qq
  - sudo apt-get install -qq $PACKAGE

script:
  - $EMACS --version
  - $EMACS -batch -l clj-parse-test-runner.el
