language: generic
env:
  - VERSION=24.3.1 EMACS=emacs PPA=ppa:ubuntu-elisp PACKAGE=emacs-snapshot
  - VERSION=25.2.2 EMACS=emacs-25.2 PPA=ppa:kelleyk/emacs PACKAGE=emacs25
  - VERSION=25.2.2 EMACS=emacs-25.2 PPA=ppa:kelleyk/emacs PACKAGE=emacs25 CLJ_PARSE_LINT=true

matrix:
  allow_failures:
    - env: VERSION=25.2.1 EMACS=emacs-25.2 PPA=ppa:kelleyk/emacs PACKAGE=emacs25 CLJ_PARSE_LINT=true

before_install:
  - sudo add-apt-repository -y $PPA
  - sudo apt-get update -qq
  - sudo apt-get install -qq $PACKAGE

script:
  - $EMACS --version
  - $EMACS --version | grep $VERSION
  - $EMACS -batch -l clj-parse-test-runner.el
